name: library_kline
description: A new Flutter package.
version: 0.0.1

environment:
  sdk: ">=2.18.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  #GetX状态管理框架
  get: ^4.6.1
  # 本地存储
  get_storage: ^2.0.3
  flutter_screenutil: ^5.9.0
  decimal: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
