platform :ios, '12.0'
source 'https://cdn.cocoapods.org/'
source 'https://github.com/SumSubstance/Specs.git'
use_frameworks!
target 'Chainup' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  
  pod 'EXFlutterKLineKit', :git => 'ssh://stash.dw2nn.com:7999/app/exflutterklinekit.git', :commit=>'a76bcb83016890736bdc059534a85e83cdd762ea' # 5.9.4

  
  pod 'EXKit', :git => "ssh://git@stash.dw2nn.com:7999/app/exkit.git",:commit=>'a973e3715e3b3e4d16b44c7f83295c6bba83519b' #6.0.0_5.3.3_private
  # EXLookin is for debug only, works with LookinServer and Lookin app.
  pod 'EXLookin', :configurations => ['Debug'], :git => 'ssh://git@stash.dw2nn.com:7999/app/exkit.git', :tag => '1.2.0'
#
  pod 'Swap', :git => "ssh://git@stash.dw2nn.com:7999/app/excontractsdk-ios.git",:commit=>'c69650d61976fc9bc0efd14d0dad0d47637849db' # origin/6.0.0_5.3.3_private
#
#  pod 'EXKit', :path => '/Users/chainup/Desktop/exkit'
#  pod 'EXKit', :path =>'/Users/chaiweidong/Desktop/cwd_work/sas_work/exkit'
#    pod 'Swap', :path => '/Users/chainup/Desktop/excontractsdk-ios'


#
#  pod 'EXKit', :path => '/Users/youbin/work/saas/EXKit'
#  pod 'Swap', :path => '/Users/youbin/work/bigclient/excontractsdk-ios'  #origin/5.9.4_private


  pod 'YYText', :path => './YYText-1.0.7'
  pod 'Firebase/Analytics','8.13.0'
  pod 'Firebase/Crashlytics','8.13.0'
  pod 'YYModel', '1.0.4'
  pod 'IdensicMobileSDK', '1.27.0'
  pod 'Starscream' , '3.1.1'
  pod 'MJExtension', '3.0.15.1'
  pod 'MJRefresh', '3.1.15.7'
  pod 'Blueprints', '0.13.1'
  pod 'DZNEmptyDataSet', '1.8.1'
  pod 'HandyJSON', '5.0.2'
  pod 'IQKeyboardManagerSwift','6.5.11'
  pod 'JXPagingView', '2.1.2'
  pod 'JXSegmentedView', '1.3.0'
  pod 'Moya', '15.0.0'
  pod 'Reachability', '3.2'
  pod 'RxCocoa', '6.5.0'
  pod 'RxRelay', '6.5.0'
  pod 'RxSwift', '6.5.0'
  pod 'SKPhotoBrowser', '7.1.0'
  pod 'SnapKit', '5.6.0'
  pod 'SwiftEntryKit', '2.0.0'
  pod 'SwiftEventBus', '5.0.0'
  pod 'YYCache', '1.0.4'
  pod 'YYImage', '1.0.4'
  pod 'YYWebImage', '1.0.5'
  pod 'YYModel', '1.0.4'
  
  
  pod 'GTSDK', '~> 2.4.4.0'
  pod 'DeepDiff', '~> 2.3.1'
  pod "TableViewDragger"
  pod 'Alamofire' , '5.0'
  pod 'AliyunOSSiOS', '~> 2.10.7'
  pod 'Tiercel','~> 3.2.0'
  pod 'URLNavigator','2.1.0'
  pod "dsBridge", '3.0.6'
  pod 'FSPagerView'
  pod 'PieCharts', :git=>'https://github.com/yozoe/PieCharts.git', :branch=>'custom'
  pod 'CYLTabBarController'
  pod 'lottie-ios', '4.2.0'
  pod 'Reusable', '~> 4.1.1'
  pod 'LookinServer/Swift', '1.2.6', :configurations => ['Debug']
  pod 'SkeletonView', '~>1.30.4'
  pod 'FMDB', '2.7.5'
end

#post_install do |installer|
#  installer.pods_project.targets.each do |target|
#    if ['PieCharts'].include? target.name
#      target.build_configurations.each do |config|
#        config.build_settings['SWIFT_VERSION'] = '4.2'
#      end
#    end
#  end
#  installer.generated_projects.each do |project|
#    project.targets.each do |target|
#      target.build_configurations.each do |config|
#        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
#      end
#    end
#  end
#end



pre_install do |installer|
  Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
end

post_install do |installer|
#  if ex_debug_flutter
#    flutter_post_install(installer) if defined?(flutter_post_install)
#  end
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
    end
    if ['PieCharts'].include? target.name
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '4.2'
      end
    end
    if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
      target.build_configurations.each do |config|
        config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      end
    end
  end
end
