const Map<String, String> en_US = {
  "text": "Task Center",
  "text1": "Cash reward, easy to get",
  "text2": "Check Reward History on PC",
  "text3": "Check in for @number Consecutive Days",
  "text3_1": "Signed in for @number day in a row",
  "text4": "Check in consecutively for 7 days to enjoy double benefits(UTC+8)",
  "text5": "Checked in",
  "text6": "Check in Now",
  "text7": "Check in Successfully",
  "text8": "Confirm",
  "text9": "View reward",
  "text10":
      "After completing the task, the task reward will be distributed to your reward center in real time.",
  "text11":
      "Please complete the task within its validity. Please claim your task reward within @number days after completing the task. If the claim time is exceeded, you will not be able to claim the reward.The reward status will be updated within [5-10] minutes after completing the task.",
  "text12":
      "After completing the task, please claim your task reward before 23:59 (UTC+8) of the day. If the time is exceeded, you will not be able to claim the reward.The reward status will be updated within [5-10] minutes after completing the task.",
  "text13": "There are currently no tasks",
  "text14": "Looking forward to more tasks",
  "text15": "Cash Reward",
  "text16": "Buy",
  "text17": "Deposit",
  "text18":
      "If the task is not completed within the time limit, the task will be automatically closed and no reward can be obtained",
  "text19": "Rewarded",
  "text20": "Task Center",
  "text21": "Withdrawn",
  "text22":
      "Refers to the assets withdrawn from the reward center to the spot account",
  "text23": "Pending Withdrawal",
  "text24":
      "After reaching the specified withdrawal amount, you can withdraw all at one time. If it is not reached, you cannot withdraw; the amount in the withdrawal state is not included.",
  "text25": "Also need",
  "text26": "to withdraw to the spot account",
  "text27": "Withdraw",
  "text28": "Withdrawal to spot account",
  "text29": "Withdrawal amount equivalent",
  "text30": "Withdrawal currency",
  "text31": "Withdrawal amount",
  "text32": "All in progress",
  "text33": "Beginner's task",
  "text34": "Daily task",
  "text35": "Daily spot trading volumes",
  "text36": "Daily margin trading volumes",
  "text37": "Daily Leveraged tokens trading volumes",
  "text38": "Daily futures trading volumes",
  "text39": "Daily check-in",
  "text35_1": "Daily spot trade",
  "text36_1": "Daily margin trade",
  "text37_1": "Daily Leveraged tokens trade",
  "text38_1": "Daily futures trade",
  "text40": "First spot trading volumes",
  "text41":
      "Within @number days after new user is registered, the first spot trading buy or sell transaction in any currency pair",
  "text42": "First margin trading volumes",
  "text43":
      "Within @number days after new user is registered, the first margin trading buy or sell transaction in any currency pair",
  "text44": "First Leveraged tokens trading volumes",
  "text45":
      "Within @number days after new user is registered, the first Leveraged tokens trading buy transaction in any currency pair",
  "text46": "First futures trading volumes",
  "text47":
      "Within @number days after new user is registered, the first futures trading buy or sell transaction in any currency pair",
  "text48": "First deposit of cryptocurrency",
  "text49":
      "Within @number days after the new user registers, the first digital currency recharge or the first third-party purchase amount",
  "text40_1": "First spot trade",
  "text42_1": "First margin trade",
  "text44_1": "First Leveraged tokens trade",
  "text46_1": "First futures trade",
  "text50": "Complete",
  "text51": "Get Reward",
  "text52": "Rewarded",
  "text53": "Failed",
  "text54": "Expired",
  "text55": "Reward Expired",
  "text56": "Expiration time",
  "text57": "Deadline for collection",
  "text58": "Collection time",
  "text59": "Reward record",
  "text60": "Reward Overview",
  "text61": "Withdrawal Record",
  "text62": "Currency",
  "text63": "Time",
  "text64": "Amount",
  "text65": "Withdrawal Converted Amount(USDT)",
  "text66": "State",
  "text67": "Reward currency",
  "text68": "Total Rewards",
  "text69": "Withdrawn",
  "text70": "Pending Withdrawal",
  "text71": "Pending Withdrawal Equivalent(USDT)",
  "text72": "Task type",
  "text73": "Task name",
  "text74": "Reward amount",
  "text75": "Equivalent amount(USDT)",
  "text76": "Time",
  "text77": "Advanced task",
  "text78": "Withdrawal",
  "text79": "Completed",
  "text80": "Reward Center",
  "text81": "Easy Task",
  "text82": "Get Cash reward",
  "text83": "Tips",
  "text84": "Before checking in, You need to complete the following settings",
  "text85": "Personal Verification",
  "text86": "Google Authenticator",
  "text87": "Phone Number Verification",
  "text88": "Canceled",
  "text89": "Go to settings",
  "text90": "Bind Mobile Phone or GA",
  "text91": "Bind Email or GA",
  'cp_marker_kline_text_dealTime': 'Time',
  'cp_marker_kline_text_open': 'Open',
  'cp_marker_kline_text_close': 'Close',
  'cp_marker_kline_text_volume': 'Filled',
  'cp_marker_kline_text_high': 'High',
  'cp_marker_kline_text_low': 'Low',
  'cp_kline_info1': 'Change',
  'cp_kline_info2': 'Change%',
  "etf_notes_explain_info": "Leveraged tokens Info",
  "etf_info_lever": "Margin(Target/Actual)",
  "etf_info_rules": "Timing Adjustment Rules",
  "etf_info_rules_no": "Irregular Position Adjustment",
  "market_text_tab_etf_info": "Information Disclosure",
  "etf_notes_explain_tips": "Risk Tip: @number1 is an Leveraged Token that tracks @number2 @number3 bar on the same day, which is more suitable for unilateral trading and short-term holding. The product fluctuates greatly and has the risk of net wear.",
  "etf_notes_multipleL": "Up @number times",
  "etf_notes_multipleS": "down @number times",
  "market_text_tab_etf_rule": "Adjustment Information",
  "etf_notes_title_mul": "%sleverage multiple",
  "etf_notes_title_action_long": "Buy long",
  "etf_notes_title_action_short": "Sell short",
  "etf_notes_auto_lever_time": "Daily 00:00 (GMT+8)",
  "etf_notes_manual_lever_time":
      "Actual leverage multiple reached @number times",
  "etf_notes_manual_lever_tran": "What is position adjustment？",
  "etf_notes_manual_lever_tran_info":
      "Through daily position adjustment, the system makes profit increase and loss reduction of contract leverage positions in the bottom levels of Leveraged Tokens. This ensures that the user's leverage ratio is consistent with the agreed ratio.Leveraged Tokens are divided into two kinds: timed position adjustment and no timed position adjustment, in which timed position adjustment refers that the platform will at the daily fixed time point execute position rebalancing management, used to ensure that Leveraged Token is in the agreed multiple leverage at the beginning of the day;A no timed position adjustment refers to a temporary position adjustment when the actual leverage multiple of a Leveraged Token exceeds a certain level within a day, and the position is the agreed multiple leverage after the position adjustment",
  "etf_notes_lever_next_if": "Rebalancing Mechanism",
  "etf_notes_lever_manual": "1、Irregular Rebalance：leverage multiple>=",
  "etf_notes_lever_auto": "2、Regular Rebalance：daily 00:00（GMT+8）",
  "etf_text_networth_current": "Current net value",
  "market_text_tab_etf_rule_sl": "Rebalancing Rules",
  "market_text_tab_etf_rule_list": "Adjustment Record",
  "sl_str_funds_rate": "Funding Rate",
  "market_text_publishtime": "Issuance Time",
  "market_text_publishTotal": "Total Supply",
  "market_text_coinHomepage": "Official Website",
  "market_text_coinInfo": "Introduction",
  "market_text_currentTotal": "Circulating Supply",
  "market_text_blockSearch": "Block Explorer",
  "cl_volume_str": "Volume",
  "cl_price_str": "Price",
  "cl_newtrade_text4": "Time",
  "market_tab_etf_type_auto_no": "Irregular Rebalance",
  "market_tab_etf_type_auto": "Regular Rebalance",
  "market_tab_etf_tran": "Net value at rebalancing",
  "market_tab_etf_before": "Pre-Rebalance leverage",
  "market_tab_etf_after": "Post-Rebalance leverage",
  "market_tab_etf_leverage_current": "Current leverage",
  "kline_action_depth": "Depth",
  "kline_action_depth_buy": "Buy",
  "kline_action_depth_sell": "Sell",
  "common_action_showMore": "More",
  "contract_action_buy": "Buy",
  "contract_action_sell": "Sell",
  "kline_Line": "Line",
  "kline_1min": "1min",
  "kline_5min": "5min",
  "kline_15min": "15min",
  "kline_30min": "30min",
  "kline_60min": "1h",
  "kline_4h": "4h",
  "kline_1day": "1d",
  "kline_1week": "1w",
  "kline_1month": "1m",
  "kline_algorithm_set": "Set",
  "kline_algorithm_main": "Main",
  "kline_algorithm_sub": "Sub",
  "kline_action_entrustMentOrder": "Order Book",
  "kline_action_dealHistory": "Records",
  "cp_extra_text111": "24h High",
  "cp_extra_text112": "24h Low",
  "cp_24vol_label": "24h Vol",
  "cp_24amount_label": "24h Vol",
  "kline_pop_dialog_confirm": "Confirm",
  "kline_Intervals1": "Customize Intervals",
  "kline_Intervals2": "Displayed Intervals",
  "kline_Intervals3": "Select up to 5 intervals",
  "kline_indicator_ma": "MA",
  "kline_indicator_ema": "EMA",
  "kline_indicator_boll": "BOLL",
  "kline_indicator_macd": "MACD",
  "kline_indicator_rsi": "RSI",
  "kline_indicator_kdj": "KDJ",
  "kline_indicator_wr": "WR",
  "kline_indicator_mid": "MID",
  "kline_indicator_std": "STD",
  "kline_kdj1": "Calculation period",
  "kline_kdj2": "MA period 1",
  "kline_kdj3": "MA period 2",
  "kline_indicator_Period4": "ex计算周期",
  "kline_macdShort": "Short period",
  "kline_macdLong": "Long period",
  "kline_macdMa": "MA period",
  "kline_IndicatorsSetting": "Indicators Setting",
  "cp_contract_order_history": "Order History",
  "cp_contract_order_display": "Order Display",
  "cp_overview_text20": "Mark Price",
  "cp_overview_text26": "Funding Rate",
  "cp_extra_text28": "I understand",
  "kline_order_history":
      "Displays the last 200 completed orders within 3 months",
  "guide_3": "I see",
  "kline_IndicatorsGuide2": "Support for setting parameters of indicators",
  "kline_IndicatorsGuide1": "Added indicator setting function",
  "kline_IntervalsGuide2": "Support custom displayed time intervals",
  "kline_IntervalsGuide1": "Added custom intervals",
  "kline_MA": "Moving Average",
  "kline_EMA": "Exponential Moving Average",
  "kline_BOLL": "Bollinger Bands",
  "kline_MACD": "Moving Average Convergence and Divergence",
  "kline_RSI": "Relative Strength Index",
  "kline_WR": "Williams Overbought",
  "kline_KDJ": "Stochastic Oscillator",
  "kline_reset": "Reset",
  "kline_complete": "Complete",
  "kline_fail_msg": "Load failed, Please",
  "kline_fail_msg2": "Retry",
  "task_center_timed_task_spot": "Spot Trade",
  "task_center_timed_task_futures": "Futures Trade",
  "task_center_timed_task_margin": "Margin Trade",
  "task_center_timed_task_etf": "Leveraged tokens Trade",
  "task_center_timed_task_challenge": "Challenge",
  "task_center_timed_task_participate_in_spot":
      "Participate in spot trading and win rewards worth @number @string!",
  "task_center_timed_task_participate_in_futures":
      "Participate in futures trading and win rewards worth @number @string!",
  "task_center_timed_task_participate_in_margin":
      "Participate in margin trading and win rewards worth @number @string!",
  "task_center_timed_task_participate_in_etf":
      "Participate in Leveraged tokens trading and win rewards worth @number @string!",
  "task_center_timed_task_unstart": "To be started",
  "task_center_timed_task_trade": "Trade",
  "task_center_timed_task_finished": "Completed",
  "task_center_timed_task_end": "Ended",
  "task_center_timed_task_from_start": "Starts in",
  "task_center_timed_task_from_end": "Ends in",
  "task_center_ok": "OK",
  "task_center_task_rewards_include": "The rewards are",
  "task_center_task_rewards_type_1": "Futures Bonus",
  "task_center_task_rewards_type_0": "Cash Reward",
  "rewards_center_text1": "Total Cash Rewards",
  "timed_task_detail_text1": "Complete the tasks to win exclusive rewards",
  "timed_task_detail_text2":
      "1.Transaction must be generated within the validity period of the task to be included in the task progress.",
  "timed_task_detail_text3":
      "2.After the task budget is used up, the task will automatically end.",
  "timed_task_detail_text4":
      "3.After completing the task, the task reward will be distributed to your reward center in real time.",
  "timed_task_detail_text5":
      "3.Please claim your task reward within @day days after completing the task. If the claim time is exceeded, you will not be able to claim the reward.The reward status will be updated within [5-10] minutes after completing the task.",
  "timed_task_detail_text6":
      "4.Only orders with a single order transaction volume ≥@num USDT will be included in the task progress.",
  "timed_task_detail_text7": "Task Description",
  "timed_task_detail_text8": "Task Rewards",
  "timed_task_detail_text9": "Tier 1",
  "timed_task_detail_text10": "Tier 2",
  "timed_task_detail_text11": "Tier 3",
  "timed_task_detail_text12": "Tier 1",
  "timed_task_detail_text13": "Tier 2",
  "timed_task_detail_text14": "Tier 3",
  "timed_task_detail_text15": "Cumulative trading volume",
  "timed_task_detail_text16": "Reward progress",
  "timed_task_detail_text17": "Reward validity period",
  "timed_task_detail_text18": "Get Reward",
  "timed_task_detail_text19": "Reward Expired",
  "timed_task_detail_text20": "Awardable",
  "timed_task_detail_text21":
      "There are currently no tasks \n Looking forward to more tasks",
  "timed_task_detail_text22": "No Records",
  "timed_task_detail_text23": "Futures Bonus",
  "timed_task_detail_text24": "Expiration date",
  "timed_task_detail_text25": "Use",
  "timed_task_detail_text26":
      "1.Click the ${"Use"} button and the futures bonus will be distributed to your futures account.\n2.The bonuses issued to the futures account must be useed within @day days. Any unused bonuses will be recycled by the system.",
  "timed_task_detail_text27": "Invalid voucher",
  "timed_task_detail_text28": "Used",
  "timed_task_detail_text29": "Expired",
  "timed_task_detail_text30": "Usage rules",
  "timed_task_detail_text31": "Also need",
  "timed_task_detail_text32": "to withdraw to the spot account",
  "timed_task_detail_text33": "Success",
  "timed_task_detail_text34": "",
  "timed_task_detail_text35": "Withdrawal Confrmation",
  "timed_task_detail_text36":
      "Are you sure you want to transfer all tokens to spot account",
  "timed_task_detail_text37": "View assets",
  "timed_task_detail_text38":
      "futures bonus has been distributed to your futures account, please use it in time.",
  "timed_task_detail_text39": "Futures bonus used successfully",
  "timed_task_detail_text40": "",
  "timed_task_detail_text41": "",
  "timed_task_detail_text42": "First deposit of cryptocurrency",
  "timed_task_detail_text43": "Sign up",
  "timed_task_detail_text44": "Get @amount @coin @type after signup",
  "timed_task_detail_text45":
      "Get @amount @coin @type by completing KYC verification within @number days after signup",
  "timed_task_detail_text46": "Sign-up Reward",
  "timed_task_detail_text47": "KYC Verification Reward",
  "timed_task_detail_text48": "Spot Trade Challenge",
  "timed_task_detail_text49": "Futures Trade Challenge",
  "timed_task_detail_text50": "Margin Trade Challenge",
  "timed_task_detail_text51": "Leveraged tokens Trade Challenge",
  "timed_task_detail_text52": "Details",
  "timed_task_detail_text53": "Progress",
  "timed_task_detail_text54": "Trading Tasks",
  "timed_task_detail_text55": "Verify",
  "timed_task_detail_text56": "Current",
  "timed_task_detail_text57": "Coupon",
  "timed_task_detail_text58": "Details",
  "timed_task_detail_text59": "Limited-time task",

  "task_center_01": "Check in",
  "task_center_02": "Didn't check in today",
  "task_center_03": "Checked in today",
  "task_center_04": "View task rewards",
  "task_centerk_05": "Do tasks and get rewards",
  "task_centerk_06": "Not checked in",
  "task_centerk_07": "Day@num",
  "task_centerk_08": "Please complete the identification and pass the audit.",
  "task_centerk_09": "Verify",

  ///盈亏分析页面
  "breakeven_analysis_text1": "PNL Analysis",
  "breakeven_analysis_text2": "7D",
  "breakeven_analysis_text3": "30D",
  "breakeven_analysis_text4": "Custom Time",
  "breakeven_analysis_text5": "Total Value",
  "breakeven_analysis_text6": "Today's PNL",
  "breakeven_analysis_text7": "30D PNL",
  "breakeven_analysis_text8": "Asset Net Worth",
  "breakeven_analysis_text9": "Cumulative PNL(%)",
  "breakeven_analysis_text10": "Cumulative PNL",
  "breakeven_analysis_text11": "No Asset allocation",
  "breakeven_analysis_text12":
      "Special note: Due to the complexity of relevant business data, there may be calculation errors and calculation delays. The above data are for reference only. We apologize for the inconvenience caused to you",
  "breakeven_analysis_text13":
      "Assets that do not have an equivalent BTC value are not shown in the chart",
  "breakeven_analysis_text14": "Select Start Date",
  "breakeven_analysis_text15": "Select a Time range within a 180 Day Period",
  "breakeven_analysis_text16": "Corss",
  "breakeven_analysis_text17": "Isolated",
  "breakeven_analysis_text18": "7D PNL",
  "breakeven_analysis_text19": "Today’s PNL",
  "breakeven_analysis_text20": "Start time must be less than end time",
  "breakeven_analysis_text21": "Daily PNL",
  "breakeven_analysis_text22": "Cumulative PNL",
  "breakeven_analysis_text23": "Net Transfer",
  "breakeven_analysis_text24": "Account Equity",
  "breakeven_analysis_text25": "Cumulative PNL History",
  "breakeven_analysis_text26": "Cumulative PNL",
  "breakeven_analysis_text27": "Cumulative PNL%",
  "breakeven_analysis_text28": "Cumulative BTC Trend",
  "breakeven_analysis_text29": "Asset Allocation",
  "breakeven_analysis_text30":
      "Asset Net Worth=The Total Net value of All the assets in spot account from day 1 to day N ",
  "breakeven_analysis_text31":
      "Today's PNL=Current asset total in spot account-Today's intial asset total（00:00:00 UTC+8-today's net transfer and deposit",

  "breakeven_analysis_text32":
      "Cumulative PNL(%)=Cumulative PNL/(asset in spot account from day 1+average net transfer and deposit from day 1 to day N)",
  "breakeven_analysis_text33":
      "Daily PNL =Daily final asset in spot account - Initial asset at 00:00:00 (UTC+8) - Net Transfer and Deposit",
  "breakeven_analysis_text34":
      "Profits= The sum of each day's Profit and loss from day 1 to day N",
  "breakeven_analysis_text35":
      "Asset Allocation =The display of each asset in spot account (sorted by each asset's latest market value)",
  "breakeven_analysis_text36":
      "Daily PNL=Account Equity on Day1-Account Equity on Day0-Net Transfer of Day 1",
  "breakeven_analysis_text37":
      "Cumulative PNL=Account Equity on Day N-Account Equity on Day 0 -Net Transfer from Day 1 To Day N",
  "breakeven_analysis_text38": "Select End Date",

  "common_text_downToRefresh": "Pull down to refresh",
  "common_text_triggerRefresh": "Release to refresh",
  "common_text_refreshing": "Loading…",
  "common_text_refresh_complete": "Loading completed",
  "common_text_refresh_failed": "Load failed",
  "common_text_upToRefresh": "Pull up to refresh",
  "common_text_loading": "Loading…",

  // "ex_smart_refresher_text7": "释放即可加载",
  "trade_new_coin_open_kline_days": "D",
  "trade_new_coin_open_kline_hours": "H",
  "trade_new_coin_open_kline_mins": "M",
  "trade_new_coin_open_kline_secs": "S",
  "trade_new_coin_open_kline_open_time": "Start time",
  "trade_new_coin_open_kline_countdown": "Countdown to start time",
  "network_loading_page":"Loading failed, please check the network or refresh and try again",
  "network_loading_button":"Refresh",
  "kline_loading":"K-line Loading...",
  "contract_limit":"Limit",
  "contract_limit_tp":"TP Limit",
  "contract_limit_sp":"SL Limit",
  "contract_market":"Market",
  "contract_market_tp":"TP Market",
  "contract_market_sp":"SL Market",
  "kline_cost_position":"Cost of Position",
  "kline_open_orders":"Open Orders",
  "kline_cost_position_text":"Display the Average Entry Price of the Position.",
  "kline_open_orders_text":"Display the last 10 unfilled orders, order types: Limit Order, Take Profit and Stop Loss.",
};
