const Map<String, String> zh_CN = {
  "text": "任务中心",
  "text1": "现金奖励，轻松领取",
  "text2": "请在PC端查看奖励",
  "text3": "已连续签到@number天",
  "text3_1": "已连续签到@number天",
  "text4": "连签第7天，奖励加倍(UTC+8)",
  "text5": "已签到",
  "text6": "立即签到",
  "text7": "签到成功",
  "text8": "确定",
  "text9": "查看奖励",
  "text10": "完成任务后，任务奖励将实时发放至您的奖励中心.",
  "text11":
      "请在任务有效期内完成任务。请在完成任务后的@number天内领取您的任务奖励，超过领取时间，将无法领取奖励。奖励状态将在完成任务后的【5-10】分钟内更新。",
  "text12":
      "完成任务后，请在当日23:59(UTC+8)之前领取您的任务奖励，超过领取时间，将无法领取奖励.奖励状态将在完成任务后的【5-10】分钟内更新。",
  "text13": "当前没有任务",
  "text14": "更多任务敬请期待",
  "text15": "现金奖励",
  "text16": "买币",
  "text17": "充币",
  "text18": "若超过时间未完成任务，任务将自动关闭无法获得奖励.",
  "text19": "领取成功",
  "text20": "任务中心",
  "text21": "累计已提现折合",
  "text22": "是指从奖励中心提现到币币账户的资产",
  "text23": "待提现折合",
  "text24": "达到规定的提现金额后您可以一次性全部提现，未达到则不可提现；不包含提现中状态的金额",
  "text25": "还差",
  "text26": "即可提现至币币账户",
  "text27": "提现",
  "text28": "提现至币币账户",
  "text29": "提现金额折合",
  "text30": "提现币种",
  "text31": "提现数量",
  "text32": "全部进行中",
  "text33": "新手任务",
  "text34": "每日任务",
  "text35": "每日币币交易额",
  "text36": "每日杠杆交易额",
  "text37": "每日杠杆代币交易额",
  "text38": "每日合约交易额",
  "text39": "每日签到",
  "text35_1": "每日币币交易",
  "text36_1": "每日杠杆交易",
  "text37_1": "每日杠杆代币交易",
  "text38_1": "每日合约交易",
  "text40": "首笔币币交易额",
  "text41": "新用户注册后@number天内，在币币交易区任意币对下首笔买入或卖出交易额",
  "text42": "首笔杠杆交易额",
  "text43": "新用户注册后@number天内，在杠杆交易区任意币对下首笔买入或卖出交易额",
  "text44": "首笔杠杆代币交易额",
  "text45": "新用户注册后@number天内，在杠杆代币交易区任意币对下首笔买入交易额",
  "text46": "首笔合约交易额",
  "text47": "新用户注册后@number天内，在合约交易区任意币对下首笔做多或做空交易额",
  "text48": "首笔数字货币入金",
  "text49": "新用户注册后@number天内，首笔数字货币充值或者首笔第三方买币金额",
  "text40_1": "首笔币币交易",
  "text42_1": "首笔杠杆交易",
  "text44_1": "首笔杠杆代币交易",
  "text46_1": "首笔合约交易",
  "text50": "去完成",
  "text51": "去领奖",
  "text52": "已领奖",
  "text53": "失败",
  "text54": "已过期",
  "text55": "奖励已过期",
  "text56": "过期时间",
  "text57": "领取截止时间",
  "text58": "领取时间",
  "text59": "奖励记录",
  "text60": "奖励总览",
  "text61": "提现记录",
  "text62": "提现币种",
  "text63": "时间",
  "text64": "提现数量",
  "text65": "提现金额折合(USDT)",
  "text66": "状态",
  "text67": "奖励币种",
  "text68": "奖励总额",
  "text69": "已提现金额",
  "text70": "未提现金额",
  "text71": "未提现金额折合(USDT)",
  "text72": "任务类型",
  "text73": "任务名称",
  "text74": "奖励金额",
  "text75": "折合金额(USDT)",
  "text76": "发放时间",
  "text77": "进阶任务",
  "text78": "提现中",
  "text79": "提现完成",
  "text80": "奖励中心",
  "text81": "轻松做任务",
  "text82": "领取现金奖励",
  "text83": "温馨提示",
  "text84": "签到前，您需要完成以下设置",
  "text85": "实名认证",
  "text86": "绑定谷歌验证",
  "text87": "绑定手机验证",
  "text88": "取消",
  "text89": "去设置",
  "text90": "绑定手机或谷歌验证",
  "text91": "绑定邮箱或谷歌验证",
  "cp_marker_kline_text_dealTime": "时间",
  "cp_marker_kline_text_open": "开",
  "cp_marker_kline_text_close": "收",
  "cp_marker_kline_text_volume": "成交量",
  "cp_marker_kline_text_high": "高",
  "cp_marker_kline_text_low": "低",
  "cp_kline_info1": "涨跌额",
  "cp_kline_info2": "涨跌幅",
  "etf_notes_explain_info": "杠杆代币介绍",
  "etf_info_lever": "杠杆(目标/实际)",
  "etf_info_rules": "定时调仓规则",
  "etf_info_rules_no": "不定时调仓规则",
  "etf_notes_explain_tips": "风险提示：@number1是追踪@number2当日@number3的杠杆代币，更适合单边行情下交易及短期持有。该产品波动较大有净值磨损风险。",
  "etf_notes_multipleL": "涨幅@number倍",
  "etf_notes_multipleS": "跌幅@number倍",
  "market_text_tab_etf_info": "信息披露",
  "market_text_tab_etf_rule": "调仓信息",
  "etf_notes_title_mul": "%s倍杠杆",
  "etf_notes_title_action_long": "做多",
  "etf_notes_title_action_short": "做空",
  "etf_notes_auto_lever_time": "每日00:00(GMT+8)",
  "etf_notes_manual_lever_time": "实际杠杆倍数达到@number倍",
  "etf_notes_manual_lever_tran": "调仓是什么？",
  "etf_notes_manual_lever_tran_info":
      "系统通过每日调仓，对杠杆代币底层对应的合约杠杆仓位进行盈利加仓、亏损减仓。从而保证用户持有的杠杆代币的杠杆比率与约定比率保持一致。杠杆代币分为定时调仓和不定时调仓两种，其中定时调仓是指平台会在每日固定时点进行仓位的再平衡管理，用来保证杠杆代币每日日初都处于约定倍数杠杆；不定时调仓是指在日内杠杆代币的实际杠杆倍数超过一定水平时的临时调仓，调仓之后处于约定倍数杠杆。",
  "etf_notes_lever_next_if": "下次调仓触发条件",
  "etf_notes_lever_manual": "1、不定时调仓：杠杆倍数>=",
  "etf_notes_lever_auto": "2、定时调仓：每日 00:00（GMT+8）",
  "etf_text_networth_current": "当前净值",
  "market_text_tab_etf_rule_sl": "调仓规则",
  "market_text_tab_etf_rule_list": "调仓记录",
  "sl_str_funds_rate": "资金费率",
  "market_text_publishtime": "发行时间",
  "market_text_publishTotal": "发行总量",
  "market_text_coinHomepage": "官网",
  "market_text_coinInfo": "简介",
  "market_text_currentTotal": "流通总量",
  "market_text_blockSearch": "区块查询",
  "cl_volume_str": "数量",
  "cl_price_str": "价格",
  "cl_newtrade_text4": "时间",
  "market_tab_etf_type_auto_no": "不定时调仓",
  "market_tab_etf_type_auto": "定时调仓",
  "market_tab_etf_tran": "调仓时净值",
  "market_tab_etf_before": "调仓前杠杆",
  "market_tab_etf_after": "调仓后杠杆",
  "market_tab_etf_leverage_current": "当前杠杆",
  "kline_action_depth": "深度",
  "kline_action_depth_buy": "买盘",
  "kline_action_depth_sell": "卖盘",
  "common_action_showMore": "更多",
  "contract_action_buy": "买入",
  "contract_action_sell": "卖出",
  "kline_Line": "分时",
  "kline_1min": "1分",
  "kline_5min": "5分",
  "kline_15min": "15分",
  "kline_30min": "30分",
  "kline_60min": "1时",
  "kline_4h": "4时",
  "kline_1day": "1日",
  "kline_1week": "1周",
  "kline_1month": "1月",
  "kline_algorithm_set": "指标设置",
  "kline_algorithm_main": "主图",
  "kline_algorithm_sub": "副图",
  "kline_action_entrustMentOrder": "委托挂单",
  "kline_action_dealHistory": "成交记录",
  "cp_extra_text111": "24h 最高价",
  "cp_extra_text112": "24h 最低价",
  "cp_24vol_label": "24h 成交量",
  "cp_24amount_label": "24h 成交额",
  "kline_reset": "重置",
  "kline_pop_dialog_confirm": "确认",
  "kline_Intervals1": "自定义周期",
  "kline_Intervals2": "展示周期",
  "kline_Intervals3": "最多选择 5个周期",
  "kline_IndicatorsSetting": "指标设置",
  "cp_contract_order_history": "历史委托",
  "cp_contract_order_display": "订单显示",
  "cp_overview_text20": "标记价格",
  "cp_overview_text26": "资金费率",
  "cp_extra_text28": "我知道了",
  "kline_order_history": "显示3个月内最近200条有成交的订单",
  "guide_3": "我知道了",
  "kline_IndicatorsGuide2": "支持设置指标的参数",
  "kline_IndicatorsGuide1": "新增指标设置",
  "kline_IntervalsGuide2": "支持自定义显示的时间周期",
  "kline_IntervalsGuide1": "新增自定义周期",
  "kline_MA": "MA 移动平均线",
  "kline_EMA": "EMA 指数移动平均线",
  "kline_BOLL": "BOLL 布林线",
  "kline_MACD": "MACD 指数平滑异同移动平均线",
  "kline_RSI": "RSI 相对强弱指标",
  "kline_WR": "WR 威廉姆斯指标",
  "kline_complete": "完成",
  "kline_KDJ": "KDJ 随机指标",
  "kline_kdj1": "计算周期",
  "kline_kdj2": "移动平均周期1",
  "kline_kdj3": "移动平均周期2",
  "kline_macdShort": "短周期",
  "kline_macdLong": "长周期",
  "kline_macdMa": "移动平均周期",
  "kline_fail_msg": "加载失败，请",
  "kline_fail_msg2": "重试",
  "task_center_timed_task_spot": "现货交易",
  "task_center_timed_task_futures": "合约交易",
  "task_center_timed_task_margin": "杠杆交易",
  "task_center_timed_task_etf": "杠杆代币交易",
  "task_center_timed_task_challenge": "挑战",
  "task_center_timed_task_participate_in_spot": "参与现货交易，最高领取@number @string奖励!",
  "task_center_timed_task_participate_in_futures":
      "参与合约交易，最高领取@number @string奖励!",
  "task_center_timed_task_participate_in_margin":
      "参与杠杆交易，最高领取@number @string奖励!",
  "task_center_timed_task_participate_in_etf": "参与杠杆代币交易，最高领取@number @string奖励!",
  "task_center_timed_task_unstart": "未开始",
  "task_center_timed_task_trade": "交易",
  "task_center_timed_task_finished": "已完成",
  "task_center_timed_task_end": "已结束",
  "task_center_timed_task_from_start": "距任务开始",
  "task_center_timed_task_from_end": "距任务结束",
  "task_center_ok": "好的",
  "task_center_task_rewards_include": "任务奖励包含",
  "task_center_task_rewards_type_1": "合约赠金",
  "task_center_task_rewards_type_0": "现金奖励",
  "rewards_center_text1": "总奖励金",
  "timed_task_detail_text1": "快来完成任务，领取专属福利",
  "timed_task_detail_text2": "1、必须在任务有效期内产生的交易额才计入任务进度中。",
  "timed_task_detail_text3": "2、任务预算使用完毕后，任务将自动结束。",
  "timed_task_detail_text4": "3、完成任务后，任务奖励将实时发放至您的奖励中心。",
  "timed_task_detail_text5":
      "3、在完成任务后的@day天内领取您的任务奖励，超过领取时间，将无法领取奖励。奖励状态将在完成任务后的【5-10】分钟内更新。",
  "timed_task_detail_text6": "4、单笔订单成交额≥@num USDT的订单才会计入任务进度中。",
  "timed_task_detail_text7": "任务描述",
  "timed_task_detail_text8": "任务奖励",
  "timed_task_detail_text9": "第一级奖励",
  "timed_task_detail_text10": "第二级奖励",
  "timed_task_detail_text11": "第三级奖励",
  "timed_task_detail_text12": "第一级",
  "timed_task_detail_text13": "第二级",
  "timed_task_detail_text14": "第三级",
  "timed_task_detail_text15": "任务累计交易量",
  "timed_task_detail_text16": "奖励解锁进度",
  "timed_task_detail_text17": "奖励有效期",
  "timed_task_detail_text18": "领奖",
  "timed_task_detail_text19": "奖励已过期",
  "timed_task_detail_text20": "可领奖",
  "timed_task_detail_text21": "当前没有任务 \n更多任务敬请期待",
  "timed_task_detail_text22": "暂无数据",
  "timed_task_detail_text23": "合约赠金券",
  "timed_task_detail_text24": "有效期",
  "timed_task_detail_text25": "使用",
  "timed_task_detail_text26":
      "1、点击”使用“按钮，合约赠金将发放至您的合约账户中。\n2、发放至合约账户的赠金请在@day天内进行交易，超时未使用的赠金将被系统回收。",
  "timed_task_detail_text27": "失效优惠券",
  "timed_task_detail_text28": "已使用",
  "timed_task_detail_text29": "已失效",
  "timed_task_detail_text30": "使用规则",
  "timed_task_detail_text31": "还差",
  "timed_task_detail_text32": "即可提现至币币账户",
  "timed_task_detail_text33": "提现成功",
  "timed_task_detail_text34": "系统异常，请联系客服",
  "timed_task_detail_text35": "提现确认",
  "timed_task_detail_text36": "您是否要将所有代币全部提现至币币账户",
  "timed_task_detail_text37": "查看资产",
  "timed_task_detail_text38": "合约赠金已发放至您的合约账户，请及时使用。",
  "timed_task_detail_text39": "合约赠金使用成功",
  "timed_task_detail_text40": "数字货币充值",
  "timed_task_detail_text41": "法币充值",
  "timed_task_detail_text42": "首笔数字货币充值",
  "timed_task_detail_text43": "注册",
  "timed_task_detail_text44": "完成注册即可获得@amount @coin @type",
  "timed_task_detail_text45": "新用户注册后@number天内，完成KYC认证即可获得@amount @coin @type",
  "timed_task_detail_text46": "注册奖励",
  "timed_task_detail_text47": "KYC认证奖励",
  "timed_task_detail_text48": "现货交易挑战",
  "timed_task_detail_text49": "合约交易挑战",
  "timed_task_detail_text50": "杠杆交易挑战",
  "timed_task_detail_text51": "杠杆代币交易挑战",
  "timed_task_detail_text52": "任务详情",
  "timed_task_detail_text53": "任务进度",
  "timed_task_detail_text54": "交易任务",
  "timed_task_detail_text55": "认证",
  "timed_task_detail_text56": "待提现",
  "timed_task_detail_text57": "优惠券",
  "timed_task_detail_text58": "奖励明细",
  "timed_task_detail_text59": "限时任务",

  "task_center_01": "签到",
  "task_center_02": "今日未签到",
  "task_center_03": "今日已签到",
  "task_center_04": "查看任务奖励",
  "task_centerk_05": "做任务领奖励",
  "task_centerk_06": "未签到",
  "task_centerk_07": "第@num天",
  "task_centerk_08": "请提交实名认证信息并通过审核",
  "task_centerk_09": "去认证",
  "trade_new_coin_open_kline_days": "天",
  "trade_new_coin_open_kline_hours": "时",
  "trade_new_coin_open_kline_mins": "分",
  "trade_new_coin_open_kline_secs": "秒",
  "trade_new_coin_open_kline_open_time": "开盘时间",
  "trade_new_coin_open_kline_countdown": "距离时间",

  ///盈亏分析页面
  "breakeven_analysis_text1": "盈亏分析",
  "breakeven_analysis_text2": "7日",
  "breakeven_analysis_text3": "30日",
  "breakeven_analysis_text4": "自定义",
  "breakeven_analysis_text5": "总资产",
  "breakeven_analysis_text6": "今日盈亏",
  "breakeven_analysis_text7": "30日盈亏",
  "breakeven_analysis_text8": "资产总值",
  "breakeven_analysis_text9": "累计收益率",
  "breakeven_analysis_text10": "累计收益",
  "breakeven_analysis_text11": "无资产分布",
  "breakeven_analysis_text12":
      "特别说明：\n由于相关业务数据复杂，可能存在计算误差及计算延迟情况，以上数据仅供参考，给您带来的不便，敬请谅解",
  "breakeven_analysis_text13": "图表中未显示没有等值 BTC 价值的资产",
  "breakeven_analysis_text14": "开始时间",
  "breakeven_analysis_text15": "仅支持查询180天内数据",
  "breakeven_analysis_text16": "全仓",
  "breakeven_analysis_text17": "逐仓",
  "breakeven_analysis_text18": "7日盈亏",
  "breakeven_analysis_text19": "每日收益",
  "breakeven_analysis_text20": "开始时间必须小于结束时间",
  "breakeven_analysis_text21": "日收益额",
  "breakeven_analysis_text22": "累计盈亏",
  "breakeven_analysis_text23": "净划入",
  "breakeven_analysis_text24": "账户权益",
  "breakeven_analysis_text25": "历史累计盈亏",
  "breakeven_analysis_text26": "累计盈亏",
  "breakeven_analysis_text27": "累计盈亏率",
  "breakeven_analysis_text28": "累计BTC趋势",
  "breakeven_analysis_text29": "资产分布",
  "breakeven_analysis_text30": "第1日到第N日的每日账户净值",
  "breakeven_analysis_text31":
      "今日盈亏 = 当前币币账户资产 - 今日0点币币账户资产（00:00:00 UTC+8） - 今天的净充值和净划入",
  "breakeven_analysis_text32":
      "累计收益率：累计盈亏 /（第1日的初始账户余额 + 第1日至第N日期间的每日累计平均净划入和充值）",
  "breakeven_analysis_text33": "每日盈亏 = 每日日终账户资产 - 每日0点账户资产 - 当天的净充值和净划入",
  "breakeven_analysis_text34": "第1日到第N日的累计盈亏",
  "breakeven_analysis_text35": "当前币币账户内按照最新市场价格计算各币种总值从高到低排列",
  "breakeven_analysis_text36": "日收益额 = 第1天的账户权益 - 第0天的账户权益 - 第0天到第1天的净划入",
  "breakeven_analysis_text37": "累计盈亏 = 第N天的账户权益 - 第0天的账户权益 - 第1天到第N天的净划入",
  "breakeven_analysis_text38": "结束时间",

  "common_text_downToRefresh": "下拉可刷新",
  "common_text_triggerRefresh": "释放即可刷新",
  "common_text_refreshing": "正在玩命加载中...",
  "common_text_refresh_complete": "加载完成",
  "common_text_refresh_failed": "加载失败",
  "common_text_upToRefresh": "上拉可刷新",
  "common_text_loading": "加载中...",
  // "ex_smart_refresher_text7": "释放即可加载",
  "network_loading_page":"加载失败，请检查网络或刷新重试",
  "network_loading_button":"刷新",
  "kline_loading":"加载中...",
  "contract_limit":"限价",
  "contract_limit_tp":"限价止盈",
  "contract_limit_sp":"限价止损",
  "contract_market":"市价",
  "contract_market_tp":"市价止盈",
  "contract_market_sp":"市价止损",
  "kline_cost_position":"持仓成本",
  "kline_open_orders":"当前委托",
  "kline_cost_position_text":"显示仓位的开仓均价",
  "kline_open_orders_text":"显示近10个未成交的订单，订单类型：限价委托、止盈止损。",
};
